# Generated by Django 5.2.7 on 2025-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="cgpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="semester_scores",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
